name: PR Checks
on: [pull_request]
jobs:
  install_modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Add pnpm store path to env var
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            **/node_modules
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

  lint:
    needs: install_modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/base-setup
        name: Base Setup
      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile
      - name: Generate dummy .env.production
        run: ./scripts/generate-dummy-dotenv.sh
      - name: Run linting
        run: pnpm run lint

  format:
    needs: install_modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/base-setup
        name: Base Setup
      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile
      - name: Generate dummy .env.production
        run: ./scripts/generate-dummy-dotenv.sh
      - name: Run formatting
        run: pnpm run format:check

  build:
    needs: install_modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/base-setup
        name: Base Setup
      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile
      - name: Generate dummy .env.production
        run: ./scripts/generate-dummy-dotenv.sh
      - name: Building app
        run: pnpm run build
      - name: Cache build
        uses: actions/cache/save@v4
        with:
          path: .next
          key: ${{ runner.os }}-build-store-${{ hashFiles('./src') }}
